Python의 Numpy는 List와 상호 변환이 가능하다

In [1]:
import numpy as np
array = np.array([1,2,3])
print(array.size)
print(array.dtype)
print(array[2])

3
int32
3


In [2]:
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4, 4), dtype=float)
print(array2)

array3 = np.ones((3, 3), dtype=str)
print(array3)

array4 = np.random.randint(0, 1, (3,3))
print(array4)

array5 = np.random.normal(0, 1, (3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 0.19981227 -0.07836953 -0.05193829]
 [-0.89039161 -2.1146206  -0.24797098]
 [-0.75484665  0.42574442 -1.37825424]]


In [3]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [4]:
array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [5]:
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))
print(array2.shape)

(2, 2)


In [9]:
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)
print(left.shape)
print(array)
print(right.shape)
print(right[1][1])
print(left)
print(right)


(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
7
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
